### ISSUE TITLE
Send Matrix Encrypted Messages to the Signal Puppet?

### ISSUE THREAD

**Issue by antonizoon** [matrix-hacks/matrix-puppet-signal#10]
Encryption is a key feature of Signal, since otherwise it would be pointless to use it and Riot's unencrypted channels would leak data.

However, is it possible to enable Riot's existing encryption system and use that to transport to the Signal puppet? This way if I trust the machine the puppet runs on, at least I know where it's getting decrypted. 

Not sure how well this works for bots to implement? Since matrix allows multiple devices to be used each with their own revokable encryption key, maybe the bot needs to whitelist each one? Something worth investigating.

**Comment by Sorunome** [comment]
that would still yield the puppet as MITM who could decrypt messages, just so you know.

That being said, IMO such a feature would be great, too!

**Comment by ara4n** [comment]
this may be acceptable if the bridge was run on a user-controlled box :)

**Comment by nr23730** [comment]
Sorry to disappoint you... But the messages will be encrypted just before sending, including all metadata and will be decrypted on the other side right after receiving. This also needs your private key that will be stored inside the client.
So it's not possible to encrypt the messages as you don't give your private key to the matrix server and will not be able to pack a message with all required header information.
