### ISSUE TITLE
Unable to send messages from matrix -> signal

### ISSUE THREAD

**Issue by mcrosson** [matrix-hacks/matrix-puppet-signal#11]
I was able to get the signal puppet linked and receiving messages.

However, whenever I try to send a message from matrix -> signal messages aren't going through. All I see in the log is "Receive a read event from ourself"

Is this a known issue?

**Comment by kfatehi** [comment]
@mcrosson sorry for not responding. Signal bridge works fine on my end. Did it start working properly for you in the end?

**Comment by mcrosson** [comment]
@kfatehi yes, I had the port/url wrong on the registration part.

I mis-read the whole 'your-bridge-server-here' piece wrong one too many times.

Once I figured that out it started working.

I did also figure out that you can't seem to puppet 2 signal accounts from a single server. Still need to find out a way to prefix things properly so I can puppet multiple signal accounts to a single matrix account.

**Comment by kfatehi** [comment]
Cool I'm glad. Yeah so this typescript rewrite https://github.com/matrix-hacks/matrix-puppet-server actually is designed to support multiple puppets on a single server (multiple networks and multiple identities on each). @Sorunome would know more about that. I think there is some work involved in porting each network (e.g. matrix-puppet-signal) over to be compatible with that though. Hope that helps.
