### ISSUE TITLE
signal-cli

### ISSUE THREAD

**Issue by dreamflasher** [matrix-hacks/matrix-puppet-signal#17]
Have you considered using https://github.com/AsamK/signal-cli as the Signal backend?

**Comment by kfatehi** [comment]
I believe that I was unaware of it at the time.

**Comment by dreamflasher** [comment]
Makes sense, but it could be worth switching potentially as it would make your project a lot simpler to maintain?

**Comment by kfatehi** [comment]
Maybe, but I have 2 points:

1. It adds a dependency to Java / the JVM. Current solution doesn't add any
additional deps and takes advantage of the fact that the official client is
JavaScript already.

2. Current solution is based on an official repository from whisper, which
seems wiser than depending on a 3rd party client which might be abandoned
one day. Then again whisper could abandon their own chrome app client too
so I don't know how much this point is worth.

**Comment by dreamflasher** [comment]
Ah fair enough! It sounded like you have to do a lot of manual work to get in a new client version, if that's not the case then your solution makes sense.

**Comment by nr23730** [comment]
To be honest: The current version of signal-desktop is based on v0.39.0 which is very old and based on the Chrome App that is decrecated for more than a year right now. 

But: We don't need much of the clients functionality. We use mostly the sending and the recieving parts which are mostly based on the official JavaScript library for Signal. 

My roadmap would be the following:
1. Get more features working (in progress)
2. Upgrade to the current data format that the desktop client uses (in progress, needed for some features)
3. Upgrade to the most recent version of the JS library (if this is too hard, at least to Message API v2)
4. Remove unused parts from the client and provide a single NodeJS package for the client

So I think there is really no need to build a complete new bridge based on Java...

**Comment by dreamflasher** [comment]
Still sounds like a lot of manual work to me. But I understand that you don't want to switch programming languages. With the java library you wouldn't need to bother about 1-4, also not in future. You would need to write the glue code around it anew though.

**Comment by nr23730** [comment]
I've done a migration to the signal-desktop app that I converted from Electron to Node.js.

This seems to work great as it provides direct access to all features, include sync messages, receipts, etc.
