### ISSUE TITLE
outbound messages do not reflect on the official, linked clients

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-signal#4]
i think this is related to #3 but basically i can send messages from riot that are received successfully by my friend, and then he responds, and the response is reflected in the official client, but not the messages that i had sent from riot.

**Comment by kfatehi** [comment]
this does not appear to be in our control.

**Comment by kfatehi** [comment]
maybe it's in our control after all. leaving this open.

**Comment by nr23730** [comment]
This is related to the usage of API v1 for messages in the Chrome App.

Messages sent with API v2 will be displayed on all clients.

**Comment by nr23730** [comment]
Messages need to be synced to the other Clients using `sendSyncMessage`.
I already got it working in nr23730/node-signal-client@d91c183243968725af831ba16fb09cd75e9a31e7 and will submit pull requests soon.
