### ISSUE TITLE
put up signal-client in gh?

### ISSUE THREAD

**Issue by mitchcapper** [matrix-hacks/matrix-puppet-signal#7]
Does not really belong on this project but it doesn't seem https://www.npmjs.com/package/signal-client has a homepage.  Do you want to put it up on GH?

**Comment by kfatehi** [comment]
It's here https://github.com/matrix-hacks/node-signal-client

I must have forgotten to put it in the package.json

I will do that later today, thank you

**Comment by kfatehi** [comment]
Done, thanks for the note.
