### ISSUE TITLE
current singal-deskop issue?

### ISSUE THREAD

**Issue by mitchcapper** [matrix-hacks/matrix-puppet-signal#8]
```
git clone https://github.com/matrix-hacks/matrix-puppet-signal
cd matrix-puppet-signal/
npm install
npm run link
```

```
Error: Cannot find module '/tmp/matrix-puppet-signal/node_modules/signal-desktop/components/long/dist/Long'
    at Function.Module._resolveFilename (module.js:470:15)
```

**Comment by kfatehi** [comment]
It actually has to do with how I find the path to vendor libs... it breaks link. Check out signalRequire:

https://github.com/matrix-hacks/node-signal-client/blob/master/index.js#L14

Do you know a better way? I think I cannot use require.resolve because signal-desktop does not define a main script.

**Comment by mitchcapper** [comment]
Ah it is actually due to the fact that npm does not support git clones with sub modules:
https://github.com/npm/npm/issues/6700
so those components do not exist.  Manually cloning singal-desktop fixed it.  The ticket has a few suggestions on how to put it into a package.json.
Well do further tickets under the proper repo.

**Comment by kfatehi** [comment]
Cool -- thanks

**Comment by mcrosson** [comment]
@mitchcapper how did you manually clone signal-desktop.

I'm receiving the exact same error and am new to npm. I'm not sure what you mean by 'manually cloning signal-desktop' means

**Comment by kfatehi** [comment]
@mcrosson I think he means that he cloned this repository manually into the node_modules directory rather than relying on `npm` to do this properly: https://github.com/matrix-hacks/node-signal-client/blob/master/package.json#L26

Meaning his did something like this:
```
cd node_modules
rm -rf Signal-Desktop
git clone git@github.com:WhisperSystems/Signal-Desktop
cd Signal-Desktop
git checkout v0.39.0
```

**Comment by mcrosson** [comment]
That definitely did the trick. Had to switch the S and D to lowercase though.
